export const agendaArray = [
  {
    id: 1,
    date: "13 กรกฎาคม 2567",
    startTime: "09:00",
    endTime: "09:30",
    title:
      "ปาฐกถา ปชุม ทาสุคนธ์: Digitalization and Evolution in Cardiovascular Medicine",
    speaker: "พลอากาศโท นพ.วรงค์ ลาภานันต์",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 2,
    date: "13 กรกฎาคม 2567",
    startTime: "09:30",
    endTime: "10:00",
    title: "2024 Optimal Management to Prevent Atherosclerosis",
    speaker: "นพ.นครินทร์ ศันสนยุทธ",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 2.5,
    date: "13 กรกฎาคม 2567",
    startTime: "10:00",
    endTime: "10:30",
    title: "Break and Exhibitions",
    speaker: null,
    sponsor: null,
    room: null,
  },
  {
    id: 3,
    date: "13 กรกฎาคม 2567",
    startTime: "10:30",
    endTime: "11:00",
    title: "Acute Pulmonary Embolism Management",
    speaker: "พญ.วราภรณ์ ติยานนท์",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 4,
    date: "13 กรกฎาคม 2567",
    startTime: "10:30",
    endTime: "11:00",
    title:
      "Peripheral Arterial Disease: Treatment Options Before Surgical Consultation",
    speaker: "นพ.ธิปกร ผังเมืองดี",
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
    slide: "https://sarawuthlim.com/wp-content/uploads/2024/07/PAD-PCR.pdf",
  },
  {
    id: 5,
    date: "13 กรกฎาคม 2567",
    startTime: "11:00",
    endTime: "11:30",
    title:
      "What Can We Expect in The New Change of 2024 AF Management Guidelines?",
    speaker: "นพ.ธรณิศ จันทรารัตน์",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 6,
    date: "13 กรกฎาคม 2567",
    startTime: "11:00",
    endTime: "11:30",
    title:
      "Integrated Care in Structural Heart Disease (Evaluation of PFO and ASD Closure)",
    speaker: ["พญ.วีรพร ปิ่นพานิชการ", "นพ.นครินทร์ ศันสนยุทธ"],
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
  },
  {
    id: 7,
    date: "13 กรกฎาคม 2567",
    startTime: "11:30",
    endTime: "12:10",
    title: "The NEXt Emerging Oral Therapy for Uncontrolled LDL-C",
    speaker: ["นพ.นครินทร์ ศันสนยุทธ", "นพ.ปรีชา เอื้อโรจนอังกูร"],
    sponsor: "Daiichi Sankyo",
    room: "ห้องประชุมใหญ่",
    type: "Luncheon Symposium",
  },
  {
    id: 8,
    date: "13 กรกฎาคม 2567",
    startTime: "11:30",
    endTime: "12:10",
    title: "SGLT2i ดีต่อใจ ดีต่อใคร",
    speaker: ["นพ.นราธิป ชุณหะมณีวัฒน์", "พญ.หัสยา ประสิทธิ์ดำรง"],
    sponsor: "AstraZeneca",
    room: "ห้องประชุมดุสิตธานี",
    type: "Luncheon Symposium",
  },
  {
    id: 9,
    date: "13 กรกฎาคม 2567",
    startTime: "12:10",
    endTime: "12:50",
    title: "What's the Choice to Harmonize Rate and Rhythm",
    speaker: "นพ.ธรณิศ จันทรารัตน์",
    sponsor: "Abbott Medical",
    room: "ห้องประชุมใหญ่",
    type: "Luncheon Symposium",
  },
  {
    id: 10,
    date: "13 กรกฎาคม 2567",
    startTime: "12:10",
    endTime: "12:50",
    title:
      "Gadobutrol-Enhanced CMR Imaging for Detection of Coronary Artery Disease",
    speaker: ["นพ.ไพโรจน์ ฉัตรานุกูลชัย", "พญ.หัสยา ประสิทธิ์ดำรง"],
    sponsor: "Bayer Thai",
    room: "ห้องประชุมดุสิตธานี",
    type: "Luncheon Symposium",
  },
  {
    id: 10.5,
    date: "13 กรกฎาคม 2567",
    startTime: "12:50",
    endTime: "13:00",
    title: "Break and Exhibitions",
    speaker: null,
    sponsor: null,
    room: null,
  },
  {
    id: 11,
    date: "13 กรกฎาคม 2567",
    startTime: "13:00",
    endTime: "13:30",
    title:
      "Post Cardiac Arrest Survival: What Are the Optimal Investigations and Management?",
    speaker: "นพ.ศราวุธ ลิ้มประเสริฐ",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
    slide:
      "https://sarawuthlim.com/wp-content/uploads/2024/07/2024-07-13-Cardio-Review-Post-Cardiac-Arrest.pdf",
  },
  {
    id: 12,
    date: "13 กรกฎาคม 2567",
    startTime: "13:00",
    endTime: "13:30",
    title:
      "Common Inherited Arrhythmias in Daily Practice (Brugada and Long QT syndrome)",
    speaker: "นพ.ปรีชา เอื้อโรจนอังกูร",
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
  },
  {
    id: 13,
    date: "13 กรกฎาคม 2567",
    startTime: "13:30",
    endTime: "14:00",
    title: "Congenital Heart Disease: What Internist Must Know?",
    speaker: "พญ.วีรพร ปิ่นพานิชการ",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 14,
    date: "13 กรกฎาคม 2567",
    startTime: "13:30",
    endTime: "14:00",
    title: "Multimodality Approach in CAD Management",
    speaker: ["พญ.หัสยา ประสิทธิ์ดำรง", "นพ.นครินทร์ ศันสนยุทธ"],
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
  },
  {
    id: 15,
    date: "13 กรกฎาคม 2567",
    startTime: "14:00",
    endTime: "14:30",
    title: "Non-steroidal MRA: Maximizing Cardiorenal Benefits",
    speaker: "นพ.นครินทร์ ศันสนยุทธ",
    sponsor: "Bayer Thai",
    room: "ห้องประชุมใหญ่",
    type: "Plenary Lecture",
  },
  {
    id: 16,
    date: "13 กรกฎาคม 2567",
    startTime: "14:00",
    endTime: "14:30",
    title:
      "Optimizing Anticoagulation Therapy for AF Patients: What to Do, How to Deal?",
    speaker: "นพ.ศราวุธ ลิ้มประเสริฐ",
    sponsor: "Boehringer Ingelheim",
    room: "ห้องประชุมดุสิตธานี",
    type: "Plenary Lecture",
    slide:
      "https://sarawuthlim.com/wp-content/uploads/2024/07/2024-07-13-Cardio-Review-OAC-in-AF.pdf",
  },
  {
    id: 16.5,
    date: "13 กรกฎาคม 2567",
    startTime: "14:30",
    endTime: "15:00",
    title: "Break and Exhibitions",
    speaker: null,
    sponsor: null,
    room: null,
  },
  {
    id: 17,
    date: "13 กรกฎาคม 2567",
    startTime: "15:00",
    endTime: "15:30",
    title: "Comprehensive Care of Pregnant Women with Cardiovascular Diseases",
    speaker: "พญ.วีรพร ปิ่นพานิชการ",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 18,
    date: "13 กรกฎาคม 2567",
    startTime: "15:00",
    endTime: "15:30",
    title: "Common Mistakes in CAC and Appropriate Use of Coronary CTA",
    speaker: "พญ.หัสยา ประสิทธิ์ดำรง",
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
  },
  {
    id: 19,
    date: "13 กรกฎาคม 2567",
    startTime: "15:30",
    endTime: "16:00",
    title: "History of Life",
    speaker: "ดร.วิทย์ สิทธิเวคิน",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
    type: "Invited Keynote Lecture",
    imageUrl:
      "https://btdigitalstorage.sgp1.cdn.digitaloceanspaces.com/2023/12/Adver2BTWorld-copy.jpg",
  },
  {
    id: 20,
    date: "14 กรกฎาคม 2567",
    startTime: "09:00",
    endTime: "09:30",
    title: "CIED Patient Care in OPD Setting: What to Look for?",
    speaker: "นพ.ศราวุธ ลิ้มประเสริฐ",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
    slide:
      "https://sarawuthlim.com/wp-content/uploads/2024/07/2024-07-14-Cardio-Review-CIED-for-internist.pdf",
  },
  {
    id: 21,
    date: "14 กรกฎาคม 2567",
    startTime: "09:00",
    endTime: "09:30",
    title:
      "Preoperative CVS Evaluation for Non-cardiac Surgery: Concise Review from Current Literatures",
    speaker: "พญ.หัสยา ประสิทธิ์ดำรง",
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
  },
  {
    id: 22,
    date: "14 กรกฎาคม 2567",
    startTime: "09:30",
    endTime: "10:00",
    title: "Current STEMI Management in Perspective of Thai Guidelines",
    speaker: "พญ.ธัญรัตน์ อร่ามเสรีวงศ์",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 23,
    date: "14 กรกฎาคม 2567",
    startTime: "09:30",
    endTime: "10:00",
    title: "Are All Competitive Sports Prohibited in Patients with CV Diseases",
    speaker: "นพ.ปรีชา เอื้อโรจนอังกูร",
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
  },
  {
    id: 24,
    date: "14 กรกฎาคม 2567",
    startTime: "10:00",
    endTime: "10:30",
    title: "Break and Exhibitions",
    speaker: null,
    sponsor: null,
    room: null,
  },
  {
    id: 25,
    date: "14 กรกฎาคม 2567",
    startTime: "10:30",
    endTime: "11:00",
    title: "How do We Treat Post ACS Heart Failure in the Current Era?",
    speaker: "นพ.ธรณิศ จันทรารัตน์",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 26,
    date: "14 กรกฎาคม 2567",
    startTime: "10:30",
    endTime: "11:00",
    title: "Cardiac Amyloidosis: Interesting Case Discussion",
    speaker: ["พญ.วราภรณ์ ติยานนท์", "นพ.ศราวุธ ลิ้มประเสริฐ"],
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
    slide:
      "https://sarawuthlim.com/wp-content/uploads/2024/07/2024-07-14-Cardio-Review-Amyloid-Case.pdf",
  },
  {
    id: 27,
    date: "14 กรกฎาคม 2567",
    startTime: "11:00",
    endTime: "11:30",
    title: "Beta Blockers Revisited: Are They Worth Prescribing?",
    speaker: "นพ.ปรีชา เอื้อโรจนอังกูร",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 28,
    date: "14 กรกฎาคม 2567",
    startTime: "11:00",
    endTime: "11:30",
    title: "Revascularization in Ischemic Cardiomyopathy Update",
    speaker: ["นพ.ธิปกร ผังเมืองดี", "พญ.ธัญรัตน์ อร่ามเสรีวงศ์"],
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
  },
  {
    id: 29,
    date: "14 กรกฎาคม 2567",
    startTime: "11:30",
    endTime: "12:10",
    title:
      "SGLT2i the Guidelines Recommended to Impact Real Practice of Cardio-Renal-Metabolic Management",
    speaker: ["นพ.เอกราช อริยะชัยพาณิชย์", "นพ.ธรณิศ จันทรารัตน์"],
    sponsor: "Boehringer Ingelheim",
    room: "ห้องประชุมใหญ่",
    type: "Luncheon Symposium",
  },
  {
    id: 30,
    date: "14 กรกฎาคม 2567",
    startTime: "11:30",
    endTime: "12:10",
    title:
      "Expanding ARNI Horizons: Translating Heart Failure Across LVEF Spectrum to Essential Hypertension Management",
    speaker: ["พญ.สุภาณี สินเพิ่มสุขสกุล", "นพ.ศราวุธ ลิ้มประเสริฐ"],
    sponsor: "Novartis",
    room: "ห้องประชุมดุสิตธานี",
    type: "Luncheon Symposium",
  },
  {
    id: 31,
    date: "14 กรกฎาคม 2567",
    startTime: "12:10",
    endTime: "12:50",
    title: "ORAL GLP-1 RA: Bridging the Gap for Future",
    speaker: ["นพ.บัญชา สถิระพจน์", "นพ.ธรณิศ จันทรารัตน์"],
    sponsor: "Novo Nordisk",
    room: "ห้องประชุมใหญ่",
    type: "Luncheon Symposium",
  },
  {
    id: 32,
    date: "14 กรกฎาคม 2567",
    startTime: "12:10",
    endTime: "12:50",
    title:
      "Start Right Way to Stay Still with NOACs in Challenging AF Patients",
    speaker: ["พญ.วรรณวรางค์ วงศ์เจริญ", "นพ.ปรีชา เอื้อโรจนอังกูร"],
    sponsor: "Daiichi Sankyo",
    room: "ห้องประชุมดุสิตธานี",
    type: "Luncheon Symposium",
  },
  {
    id: 33,
    date: "14 กรกฎาคม 2567",
    startTime: "12:50",
    endTime: "13:00",
    title: "Break and Exhibitions",
    speaker: null,
    sponsor: null,
    room: null,
  },
  {
    id: 34,
    date: "14 กรกฎาคม 2567",
    startTime: "13:00",
    endTime: "13:30",
    title: "Acute Chest Pain Evaluation and How to Interpret Troponin Wisely?",
    speaker: "นพ.ธิปกร ผังเมืองดี",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 35,
    date: "14 กรกฎาคม 2567",
    startTime: "13:00",
    endTime: "13:30",
    title:
      "Stroke Prevention in AF: Oral Anticoagulant vs. Left Atrial Appendage Occlusion",
    speaker: ["นพ.ธรณิศ จันทรารัตน์", "นพ.ปรีชา เอื้อโรจนอังกูร"],
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
  },
  {
    id: 36,
    date: "14 กรกฎาคม 2567",
    startTime: "13:30",
    endTime: "14:00",
    title: "Handling the Residual Cardiovascular Risk with the New SPPARM⍺",
    speaker: "พญ.ธนัญญา บุณยศิรินันท์",
    sponsor: "Biopharm",
    room: "ห้องประชุมใหญ่",
    type: "Plenary Lecture",
  },
  {
    id: 37,
    date: "14 กรกฎาคม 2567",
    startTime: "13:30",
    endTime: "14:00",
    title: "Update Dyslipidemia Management: Highlighting on PCSK9i mAb",
    speaker: "นพ.นครินทร์ ศันสนยุทธ",
    sponsor: "Amgen",
    room: "ห้องประชุมดุสิตธานี",
    type: "Plenary Lecture",
  },
  {
    id: 38,
    date: "14 กรกฎาคม 2567",
    startTime: "14:00",
    endTime: "14:30",
    title:
      "Revascularization or Medication in Asymptomatic CAD in the CTA Screening Era",
    speaker: ["นพ.ชัยศิริ วรรณลภากร", "พญ.ธัญรัตน์ อร่ามเสรีวงศ์"],
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 39,
    date: "14 กรกฎาคม 2567",
    startTime: "14:00",
    endTime: "14:30",
    title: "Structural Change in Long Standing AF",
    speaker: "พญ.วราภรณ์ ติยานนท์",
    sponsor: null,
    room: "ห้องประชุมดุสิตธานี",
    slide:
      "https://sarawuthlim.com/wp-content/uploads/2024/07/AF-TR-and-MR.pdf",
  },
  {
    id: 40,
    date: "14 กรกฎาคม 2567",
    startTime: "14:30",
    endTime: "15:00",
    title: "Break and Exhibitions",
    speaker: null,
    sponsor: null,
    room: null,
  },
  {
    id: 41,
    date: "14 กรกฎาคม 2567",
    startTime: "15:00",
    endTime: "15:30",
    title: "The Trials that May Change My Practice",
    speaker: "แพทย์ประจำบ้านต่อยอด และ คณาจารย์",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
  {
    id: 42,
    date: "14 กรกฎาคม 2567",
    startTime: "15:30",
    endTime: "16:00",
    title: "The Ultimate Cardiovascular Quiz",
    speaker: "คณาจารย์",
    sponsor: null,
    room: "ห้องประชุมใหญ่",
  },
];
